version: '3.8'

services:
  api-dev:
    build: ./api
    image: sdpx/api:dev
    ports:
      - "8081:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db-dev
      - DB_USER=admin
      - DB_PASSWORD=db4dev$
      - DB_NAME=users
    networks:
      - dev-network
    depends_on:
      - db-dev

  api-test:
    build: ./api
    image: sdpx/api:test
    ports:
      - "8082:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db-test
      - DB_USER=admin
      - DB_PASSWORD=db4test$
      - DB_NAME=users
    networks:
      - test-network
    depends_on:
      - db-test

  db-dev:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: db4dev$
      MYSQL_DATABASE: users
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev-network

  db-test:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: db4test$
      MYSQL_DATABASE: users
    volumes:
      - db-test-data:/var/lib/mysql
    networks:
      - test-network

volumes:
  db-data:
  db-test-data:

networks:
  dev-network:
  test-network:
